@url_dev=http://localhost:3055/v1/api
### signup
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: 42026472b8ebb5fa19bb95a8778d3aac44a6b2c157b518f84266c013e302518bd78cce1bfd2663c9a0001b2fdfdfcfc2fad4df80bddb5e4d2c51c03150363130

{
  "name": "Shop QuanBH",
  "email": "shopquanbh@gmail.com",
  "password": "abc@1234"
}